apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-server
spec:
  to:
    kind: Service
    name: llamastack-server
    weight: 100
  port:
    targetPort: 8321
  wildcardPolicy: None

